apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: tap-gui-catalog
  description: Starter catalog with accelerators
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  targets:
    - ./components/tap-gui.yaml
    - ./groups/default-org.yaml
    - ./systems/tap-gui-system.yaml
    - ./domains/tap-gui-domain.yaml
    - https://github.com/vmware-tanzu/application-accelerator-samples/blob/main/where-for-dinner/catalog/catalog-info.yaml
